services:
  redis:
    image: redis:7.4-alpine
    container_name: smiles-render-redis
    ports:
      - 6379:6379

  smiles-render-web:
    build: .
    container_name: smiles-render-web
    env_file:
      - .env
    expose:
      - 3000
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  celery-worker:
    build: .
    container_name: smiles-render-worker
    command: celery -A src.tasks worker --loglevel=info --pool=solo
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  nginx:
    image: nginx:stable-alpine
    container_name: smiles-render-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - smiles-render-web
